let autos =[ {
    marca: "Ford",
    modelo: "Fiesta",
    precio: 150000,
    km: 90,
    color: "Azul",
    cuotas: 12,
    anio: 2019,
    patente: "APL123",
    vendido: false,
},
{
    marca: "Toyota",
    modelo: "Corolla",
    precio: 100000,
    km: 0,
    color: "Blanco",
    cuotas: 14,
    anio: 2019,
    patente: "JJK116",
    vendido: false,
},
{
    marca: "Chevrolet",
    modelo: "Corsa",
    precio: 180000,
    km: 0,
    color: "Azul",
    cuotas: 14,
    anio: 2008,
    patente: "LBK253",
    vendido: false,
},
];

module.exports = autos;